name: bvm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^0.19.0
  curved_navigation_bar: ^0.3.3
  http: ^0.12.2
  provider: ^4.3.2+2
  toast: ^0.1.5
  shared_preferences: ^0.5.10
  url_launcher: ^5.5.3
  flutter_inappwebview: ^4.0.0+4
  liquid_progress_indicator: ^0.3.2
  youtube_player_flutter: ^7.0.0+7
  sms_autofill: ^1.2.5
  share: ^0.6.5
  flutter_windowmanager: ^0.0.2
  razorpay_flutter: 
  flutter_swiper: ^1.1.6
  bubble: ^1.1.9+1
  intl: ^0.16.1
  flutter_dialogflow: ^0.1.3
  flutter_spinkit: "^4.1.2"
  cached_network_image: ^2.3.2+1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/img1.PNG
    - assets/images/bvm.PNG
    - assets/images/img2.jpeg
    - assets/images/splash.PNG
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpeg
    - assets/images/img6.jpeg
    - assets/images/img6.jpeg
    - assets/images/img8.jpeg
    - assets/images/nda.jpeg
    - assets/images/oops.jpg
    - assets/images/error.svg
    - assets/images/paytm.svg
    - assets/images/GooglePay.svg
    - assets/images/razorpay.svg
    - assets/images/Mastercard.svg
    - assets/images/visa.svg
    - assets/images/verified.svg
    - assets/images/RuPay.svg
    - assets/images/edit.svg
    - assets/images/courses.svg
    - assets/images/democlasses.svg
    - assets/images/buycourses.svg
    - assets/images/allnotes.svg
    - assets/images/gk.svg
    - assets/images/announcement.svg
    - assets/images/ourbatches.svg
    - assets/images/testseries.svg
    - assets/images/performance.svg
    - assets/images/live.svg
    - assets/images/doubts.svg
    - assets/images/assignment.svg
    - assets/images/timetable.svg
    - assets/images/user2.svg
    - assets/images/myorder.svg
    - assets/images/mycourses.svg
    - assets/images/setting.svg
    - assets/images/logout.svg
    - assets/images/share.svg
    - assets/images/log.svg
    - assets/images/test.svg
    - assets/images/password.svg
    - assets/images/user.svg
    - assets/images/otp10.svg
    - assets/images/otp1.svg
    - assets/images/edit2.svg
    - assets/images/figma1.svg
    - assets/images/figma2.svg
    - assets/images/loading.svg
    - assets/images/verify.svg
    - assets/json/chatbot.json


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-ExtraLight.ttf
         - asset: assets/fonts/Montserrat-Light.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
